### ISSUE TITLE
The Morgan Fingerprint examples on the RDKit.org page aren't running correctly

### ISSUE THREAD

**Issue by ankline04** [rdkit/rdkit#7417]
**Configuration:**

- RDKit Version: 2022.03.5
- Operating system: windows
- Python version (if relevant): 3.10.13
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from? default conda forge
- If you are not using conda: how did you install the RDKit?

**Description:**

I am trying to get bit info from morgan fingerprints built from RDkit (using AllChem.GetMorganFingerprintAsBitVect). In order to test this, I first tried to test the example on the RDkit documentation page (https://www.rdkit.org/new_docs/GettingStartedInPython.html#morgan-fingerprints) under the section 'Morgan Fingerprints (Circular Fingerprints)'

When I use this exact code from the website, it doesn't work. Particularly, in that section on the documentation page it has "fpgen = AllChem.GetMorganGenerator(radius=2)" which I had to change the AllChem to rdFingerprintGenerator because the error kept popping up that ''module 'rdkit.Chem.AllChem' has no attribute 'GetMorganGenerator' " once I changed that it ran, but then getting to the part 

ao = rdFingerprintGenerator.AdditionalOutput()
ao.CollectBitInfoMap()

The error pops up "'AdditionalOutput' object has no attribute 'CollectBitInfoMap'"

```
Your code sample here
```
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
from rdkit.Chem import AllChem

m = Chem.MolFromSmiles('c1cccnc1C')
fpgen = rdFingerprintGenerator.GetMorganGenerator(radius=2)
ao = rdFingerprintGenerator.AdditionalOutput()
ao.CollectBitInfoMap()

**Comment by bp-kelley** [comment]
Your version of python predates the current documentation.  This code works in version 2023.03.3 and greater.

**Comment by bp-kelley** [comment]
https://pypi.org/project/rdkit/ has the newer versions

**Comment by greglandrum** [comment]
> https://pypi.org/project/rdkit/ has the newer versions

As does conda-forge, which I recommend over pypi unless you have a very good reason to not be able to use conda-forge
