### PR TITLE
Compile time and runtime deprecation warnings

### PR DESCRIPTION
**Pull request by PatrickPenner**
* Used [[deprecated]] attribute to mark deprecation on cpp side
* Used RDLog to escalate deprecation warnings to python
* Deprecated non fingerprint generator fingerprint generation functions

Deprecation warnings are inserted low as possible without affecting functionality shared by the fingerprint generators. Functions that wrap fingerprint generator functionality have not been deprecated.

### CODE REVIEW

**Comment by PatrickPenner** [comment]
I talked with Greg about deprecating rdkit.Chem.MolStandardize on a module level. Although I initially implemented that, I reverted it again because it would show deprecation warning when importing rdMolStandardize as well, which I thought would be confusing.

Is the test appropriate? I didn't want to have no test at all and I wasn't sure if we wanted a test for every single deprecation. It currently just tests if deprecation warnings are correctly escalated.

**Comment by PatrickPenner** [comment]
Ubuntu dies with:
cc1plus: all warnings being treated as errors

The deprecation message test fails on windows.

Traceback (most recent call last):
  File "D:\a\1\s\rdkit\UnitTestLogging.py", line 417, in testDeprecationWarning
    self.assertEqual(captured, expected)
AssertionError: {} != {'std::cerr': '[timestamp] DEPRECATION WARNING: please use AtomPairGenerator\n'}
- {}
+ {'std::cerr': '[timestamp] DEPRECATION WARNING: please use AtomPairGenerator\n'}

The two Java builds consider deprecation attributes a syntax error:
/home/vsts/work/1/s/Code/GraphMol/Fingerprints/AtomPairs.h:80: Error: Syntax error in input(1).

**Comment by greglandrum** [comment]
@PatrickPenner looks like we'll need to switch off the deprecation warnings in the pieces of the RDKit which are implemented on top of the deprecated code in order to avoid some of the problems.

If you would like, I can take a look at the problems in the SWIG wrappers and/or the Windows builds.

**Comment by PatrickPenner** [comment]
It seems most of these issues are somehow related to the build pipeline. I thought Windows might be a specific IO flushing thing but I am using std::endl. I took a look at SWIG and that they have recently begun ignoring attributes. If we want to continue using cpp attributes we will need SWIG >=4.1 (https://www.swig.org/Doc4.1/SWIGDocumentation.html#CPlusPlus11_attributes).

Is turning off deprecation warnings something I can do or is that also deeper in the pipeline?

**Comment by greglandrum** [comment]
> If we want to continue using cpp attributes we will need SWIG >=4.1 (https://www.swig.org/Doc4.1/SWIGDocumentation.html#CPlusPlus11_attributes).

I don't think this is problematic. The wrappers build with SWIG 4.1 and it is widely available. We can switch the CI builds over to 4.1 without problems.

@bp-kelley @jones-gareth, what's your take on us forcing SWIG 4.1+?

**Comment by PatrickPenner** [comment]
I have been working around the SWIG issue using the preprocessor:
> #ifndef SWIG
> [[deprecated("please use AtomPairGenerator")]]
> #endif
I don't like these kinds of solutions but they do work. The SWIG documentation states that all they do with C++11 attributes is "crudely ignore" them, which is probably comparable.

**Comment by greglandrum** [comment]
> I have been working around the SWIG issue using the preprocessor:
> 
> > #ifndef SWIG
> > [[deprecated("please use AtomPairGenerator")]]
> > #endif
> 
> I don't like these kinds of solutions but they do work. The SWIG documentation states that all they do with C++11 attributes is "crudely ignore" them, which is probably comparable.

Yeah, I saw the changes and think they'd be ok if we absolutely need them. But if there's no good reason to maintain SWIG3 support, then I see no reason to not just allow the cleaner form.

**Comment by jones-gareth** [comment]
> > If we want to continue using cpp attributes we will need SWIG >=4.1 (https://www.swig.org/Doc4.1/SWIGDocumentation.html#CPlusPlus11_attributes).
> 
> I don't think this is problematic. The wrappers build with SWIG 4.1 and it is widely available. We can switch the CI builds over to 4.1 without problems.
> 
> @bp-kelley @jones-gareth, what's your take on us forcing SWIG 4.1+?

I'm already using SWIG 4.1 on Windows.  As long as it is easy to install on Ubuntu that should be fine.

**Comment by PatrickPenner** [comment]
Ubuntu >= 23 and Debian >= 12 have SWIG 4.1 in their default apt repositories. Unfortunately neither the Ubuntu 20 LTS running at the moment or the newer Ubuntu 22 LTS have it. SWIG 4.1 is of course available in conda.

**Comment by greglandrum** [comment]
> Ubuntu >= 23 and Debian >= 12 have SWIG 4.1 in their default apt repositories. Unfortunately neither the Ubuntu 20 LTS running at the moment or the newer Ubuntu 22 LTS have it. SWIG 4.1 is of course available in conda.

Yeah, I have been installing it from conda, that's what we do in the CI builds as well.

**Comment by jones-gareth** [comment]
It is straightforward to build SWIG on Ubuntu.  Between that and conda I am good with having to use SWIG 4.1.

**Review by greglandrum — APPROVED** [review]
I think this one is ready to go.
Once the CI builds pass I will do the merge

**Comment by greglandrum** [comment]
@PatrickPenner the failures here are due to CI configuration.
I will do a PR against your branch which will hopefully help

**Comment by greglandrum** [comment]
Merged as #7004 

Thanks for the contribution @PatrickPenner  (and for sticking it out through the overly long review process)
