### ISSUE TITLE
Boost 1.65 removes boost/python/numeric.hpp

### ISSUE THREAD

**Issue by mcs07** [rdkit/rdkit#1581]
**Description:**

RDKit fails to build with Boost 1.65.

According to the [Boost 1.65 release notes](http://www.boost.org/users/history/version_1_65_1.html):

> The boost::python::numeric API has been removed, as it is being obsoleted by boost::python::numpy.

It appears that `boost/python/numeric.hpp` is used in a few places in RDKit. Hopefully it is possible to switch to the boost numpy API while maintaining compatibility with older boost versions with the numeric API?

**Comment by thegodone** [comment]
Dear Matt,

I had the issue this morning too, I've changed the numeric.hpp to numpy.hpp
header on those files and it works:

Code/DataManip/MetricMatrixCalc/Wrap/rdMetricMatrixCalc.cpp

Code/SimDivPickers/Wrap/MaxMinPicker.cpp

Code/DataStructs/Wrap/DataStructs.cpp

Code/SimDivPickers/Wrap/HierarchicalClusterPicker.cpp

Code/Numerics/Alignment/Wrap/rdAlignment.cpp

Code/GraphMol/ReducedGraphs/Wrap/rdReducedGraphs.cpp

Code/GraphMol/MolAlign/Wrap/rdMolAlign.cpp

BR,

Guillaume



2017-09-18 22:17 GMT+02:00 Matt Swain <notifications@github.com>:

**Comment by JLVarjo** [comment]
Encountered this too. Apparently this is not pushed to master yet? (and btw, isn't the new BOOST_NUMPY definition now "APPLE"-specific only in CMakeLists.txt?)

**Comment by mbraden-work** [comment]
I am (still?) having this issue when installing rdkit using homebrew with or without --HEAD. How do I edit those files and still install using homebrew?

**Comment by greglandrum** [comment]
Working with boost 1.65 is currently a problem. I would suggest using v1.63.

**Comment by hsiaoyi0504** [comment]
@mbraden-work for more information, please refer to rdkit/homebrew-rdkit#43.

**Comment by szcc** [comment]
Guillaume(  @thegodone ),

I updated numeric.hpp to numpy.hpp in those files and I get other error like Code/DataStructs/Wrap/DataStructs.cpp:20:30: fatal error: numpy/npy_common.h: No such file or directory
 #include <numpy/npy_common.h>
RDBoost/import_array.h:5:31: fatal error: numpy/arrayobject.h: No such file or directory
 #include <numpy/arrayobject.h>
Can someone help me?
Thanks,
Sue

**Comment by mcs07** [comment]
@szcc This should already be fixed in RDKit 2017.09.2 or higher if you can upgrade.

**Comment by szcc** [comment]
Thank you. @mcs07  I downloaded the 2017.09.2 version and rerun cmake I got:
CMake Error at CMakeLists.txt:12 (install):
  install FILES given no DESTINATION!
CMake Error at CMakeLists.txt:15 (add_pytest):
  Unknown CMake command "add_pytest".

CMakeLists.txt L12:  DESTINATION ${RDKit_PythonDir}) 
When I ran 2016 version I do not need set up RDKit_PythonDir. where should I set RDKit_PythonDir to?

**Comment by szcc** [comment]
Thanks @mcs07 . I updated RDKit to 2017.09.3 and I got same error:
/rdkit-Release_2017_09_3/Code/DataStructs/Wrap/DataStructs.cpp:21:30: fatal error: numpy/npy_common.h: No such file or directory
 #include <numpy/npy_common.h>
                              ^
compilation terminated.

**Comment by szcc** [comment]
@mcs07  Thanks. It built.
