### ISSUE TITLE
#3866 seems to break Linux conda-based builds

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#3876]
Since I updated to the latest `master` my build based on `conda` libs broke with
```
libpng16.so.16: undefined reference to `inflateValidate@ZLIB_1.2.9'
```
`libpng16.so.16` is from `conda`.
Reverting #3866 fixed the problem for me.

**Comment by greglandrum** [comment]
which libraries that you're linking against come from conda?

**Comment by ptosco** [comment]
It could well be a problem in my build - it could be picking my system `zlib` rather than the `conda` one. I'll investigate further.

**Comment by ptosco** [comment]
Closing this until I gather more information on my side.

**Comment by ptosco** [comment]
OK, the fix was simple and entirely on my side, documenting it here in case someone else runs into the same issue:
I added to my `cmake` command
```
-D ZLIB_ROOT=$CONDA_PREFIX
```
to avoid that `cmake` picked my outdated system `zlib`.
