### PR TITLE
Workaround to compile with Visual Studio 2015

### PR DESCRIPTION
**Pull request by mcs07**
There is a bug in the current version of Microsoft Visual Studio 2015 that causes linker errors with boost python. For example:

    rdMolCatalog.cpp.obj : error LNK2019: unresolved external symbol "class RDKit::ROMol const volatile * __cdecl boost::get_pointer<class RDKit::ROMol const volatile >(class RDKit::ROMol const volatile *)" (??$get_pointer@$$CDVROMol@RDKit@@@boost@@YAPEDVROMol@RDKit@@PEDV12@@Z)

It appears that this is a known issue that will supposedly be fixed in a future version of Visual Studio. For more details see:

- https://connect.microsoft.com/VisualStudio/Feedback/Details/2852624
- http://stackoverflow.com/questions/38261530/unresolved-external-symbols-since-visual-studio-2015-update-3-boost-python-link

This pull request contains the changes I had to make to successfully compile with Visual Studio 2015. I basically just naively implemented the suggested workaround from the Microsoft bug tracker.

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum @mcs07 @rvianello 

Nice.  I can check to see if this compiles with the non-patched msvc 2015 that I have kept for exactly this reason, could one of you try 2010?  If it works with 2015, I might submit a conditional patch to only enable these for MSVC2015 builds just to be on the safe side.

**Comment by greglandrum** [comment]
I will give it a try on VS2010 tomorrow when I am back in Basel

**Comment by greglandrum** [comment]
This does not build with VS2010 and boost 1.56.
The errors are of the:
``` wrap_BitOps.obj : error LNK2005: "class ExplicitBitVect const volatile * __cdecl boost::get_pointer<class ExplicitBitVect const volatile >(class ExplicitBitVect const volatile *)" (??$get_pointer@$$CDVExplicitBitVect@@@boost@@YAPEDVExplicitBitVect@@PEDV1@@Z) already defined in wrap_ExplicitBV.obj [C:\Users\glandrum\RDKit_git\build64_py27\Code\DataStructs\Wrap\cDataStructs.vcxproj]
         C:\Users\glandrum\RDKit_git\build64_py27\rdkit\DataStructs\Release\cDataStructs.pyd : fatal error LNK1169: one or more multiply defined symbols found [C:\Users\glandrum\RDKit_git\build64_py27\Code\DataStructs\Wrap\cDataStructs.vcxproj]
```
variety

**Comment by JimSEOW** [comment]
I have tried compiling with Miniconda3.5 with VisualStuidio2015 Update3

I suggest a good practice to have a common open issue title: **Window: VisualStudio2015, Conda/python, boost** where windows users could share their experience on what is the best way to compile RDK.

The only way I manage is through **conda install rdk**. It install boost 1.59). I guest for python3.5, boost 1.59 would be preferred. 

This led me to switch from Boost 1.55 using VisualStuio2010 for RDK 2015 release to VisualStudio2015 for rdk 2016 release.

Request @mcs07 Please update which configurations of visual studio 2015, which boost, which python (python34 versus MiniConda3.5) 

Thanks

**Comment by greglandrum** [comment]
@mcs07 : I'm afraid I lost the thread on this one. Does the current status of the trunk build ok for you? I haven't been having problems with either VS2010 or VS2015, but I want to check in.

**Comment by mcs07** [comment]
I still need this patch to compile v2016.09.4 using the latest VS 2015 (Update 3). But after going through the arduous process of downgrading Visual Studio to 2015 Update 2, this patch isn't needed and everything compiles fine.

I'm planning to stick with this version of Visual Studio, so I personally no longer need this pull request.

**Comment by greglandrum** [comment]
ok, thanks for the update.
I did a post to the mailing list a while ago explaining the problem with VS2015 Update 3, so we have something to point people do.
I'm going to go ahead and close this.
