### ISSUE TITLE
Fails to build with Boost 1.69 (develop snapshot)

### ISSUE THREAD

**Issue by jbeich** [rdkit/rdkit#2128]
After boostorg/dynamic_bitset@a449a11a8004 build fails. See [error log](https://ptpb.pw/WJBK).

```c++
Code/GraphMol/FindRings.cpp:234:55: error: call to member function 'set' is ambiguous
    if (bitBrings[i].is_subset_of(munion)) availRings.set(i, 0);
                                           ~~~~~~~~~~~^~~
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:284:21: note: candidate function
    dynamic_bitset& set(size_type n, size_type len, bool val = true);
                    ^
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:285:21: note: candidate function
    dynamic_bitset& set(size_type n, bool val = true);
                    ^
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:286:21: note: candidate function not viable: requires 0 arguments, but 2 were provided
    dynamic_bitset& set();
                    ^
Code/GraphMol/FindRings.cpp:268:16: error: call to member function 'set' is ambiguous
      consider.set(bestJ, 0);
      ~~~~~~~~~^~~
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:284:21: note: candidate function
    dynamic_bitset& set(size_type n, size_type len, bool val = true);
                    ^
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:285:21: note: candidate function
    dynamic_bitset& set(size_type n, bool val = true);
                    ^
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:286:21: note: candidate function not viable: requires 0 arguments, but 2 were provided
    dynamic_bitset& set();
                    ^
Code/GraphMol/FindRings.cpp:270:20: error: call to member function 'set' is ambiguous
        availRings.set(bestJ, 0);
        ~~~~~~~~~~~^~~
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:284:21: note: candidate function
    dynamic_bitset& set(size_type n, size_type len, bool val = true);
                    ^
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:285:21: note: candidate function
    dynamic_bitset& set(size_type n, bool val = true);
                    ^
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:286:21: note: candidate function not viable: requires 0 arguments, but 2 were provided
    dynamic_bitset& set();
                    ^
Code/GraphMol/FindRings.cpp:273:20: error: call to member function 'set' is ambiguous
        availRings.set(bestJ, 0);
        ~~~~~~~~~~~^~~
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:284:21: note: candidate function
    dynamic_bitset& set(size_type n, size_type len, bool val = true);
                    ^
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:285:21: note: candidate function
    dynamic_bitset& set(size_type n, bool val = true);
                    ^
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:286:21: note: candidate function not viable: requires 0 arguments, but 2 were provided
    dynamic_bitset& set();
                    ^
Code/GraphMol/FindRings.cpp:1042:35: error: call to member function 'set' is ambiguous
        if (!ringFound) deadBonds.set(possibleBonds[0]->getIdx(), 1);
                        ~~~~~~~~~~^~~
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:284:21: note: candidate function
    dynamic_bitset& set(size_type n, size_type len, bool val = true);
                    ^
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:285:21: note: candidate function
    dynamic_bitset& set(size_type n, bool val = true);
                    ^
/usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:286:21: note: candidate function not viable: requires 0 arguments, but 2 were provided
    dynamic_bitset& set();
                    ^
```

**Comment by jbeich** [comment]
@jeking3, is this ambiguity expected?

**Comment by jeking3** [comment]
It was not intended, but makes sense in C++03 where bool is handled as an integer type, this makes it ambiguous.  The right thing to do is change the defaulted argument to an enumerated type that includes values of "set" and "clear" or something like that.  I opened a defect in the project.

**Comment by jbeich** [comment]
> It was not intended, but makes sense in C++03 where bool is handled as an integer type, this makes it ambiguous.

But rdkit explicitly uses C++11:

https://github.com/rdkit/rdkit/blob/7976c36b873e26bb45f82ffbb290abe9ece2a12f/CMakeLists.txt#L391
https://github.com/rdkit/rdkit/blob/7976c36b873e26bb45f82ffbb290abe9ece2a12f/CMakeLists.txt#L400

and my error log contains:

> -- The CXX compiler identification is Clang 6.0.0

which in absence of `-std=` would use C++14

**Comment by jeking3** [comment]
Could you try this and let me know?
https://github.com/boostorg/dynamic_bitset/pull/32

Thanks.

**Comment by jbeich** [comment]
I confirm, rdkit [builds fine](https://ptpb.pw/a3KQ) now.
