### PR TITLE
Exposes Get/Set Double, Int, Uint and bool props to molecules

### PR DESCRIPTION
**Pull request by bp-kelley**

### CODE REVIEW

**Comment by greglandrum** [comment]
I like the double, int, and bool versions, but UInt from Python feels somehow wrong.
If it's going to be there (and I can see that it probably should be), how about as {Get,Set}UnsignedProp()?

**Comment by greglandrum** [comment]
And if the unsigned version is there for mols, it should also be there for Atoms and Bonds

**Comment by bp-kelley** [comment]
The unsigned prop is really there as a way to manipulate unsigned data in C++ land, basically if a property is unsigned, you cannot extract it as an integer (runtime error).

If we don't want to do this, I'm happy removing it.  I would also like to add an interface:

```
> mol.GetProps() 
{"a":2.0, "b":"some string", "c": 1, "d": False}
```

For better inspection purposes as well.  If this is the case, we would need to have an Unsigned (or perhaps numpy unsigned) type as well.  (As well as vector and other types ;))

**Comment by greglandrum** [comment]
How about just calling it Unsigned instead of UInt?

**Comment by greglandrum** [comment]
My only objection to `Mol.GetProps()` is that it returns a copy of the properties (kind of) instead of a "pointer" like Mol.GetAtoms(), Mol.GetBonds(), Mol.GetConformer(), etc.

How about calling it Mol.GetPropsAsDict()?

**Comment by bp-kelley** [comment]
Sounds good.

----
Brian Kelley

**Comment by bp-kelley** [comment]
GetPropsAsDict works pretty well!

```
> m.GetPropsAsDict(includePrivate=True)
{'_MolFileInfo': 'BBtclserve11129916382D 0   0.00000     0.00000    48',
'NSC': '48', 'NCI_AIDS_Antiviral_Screen_IC50': '2.00E-04\tM\t=\t2.46E-05\t3',
'_Name': '48', 'CAS_RN': '15716-70-8', '_MolFileComments': '15716-70-8',
'NCI_AIDS_Antiviral_Screen_EC50': '2.00E-04\tM\t>\t2.00E-04\t3', 
'NCI_AIDS_Antiviral_Screen_Conclusion': 'CI'}
```

**Comment by bp-kelley** [comment]
There may be something wrong with the java builds on python 3.4
```
/home/travis/build/rdkit/rdkit/Code/JavaWrappers/gmwrapper/src-test/org/RDKit/GraphMolTest.java:67: error: cannot find symbol
	public static void assertPointEquals(Point3D pt1, Point3D pt2, double tol) {
	                                     ^
  symbol:   class Point3D
  location: class GraphMolTest
```

All the C++/Python tests pass though.

**Comment by JLVarjo** [comment]
This is great stuff, I was just about to start doing something similar myself. But how about making the int setters to set 64-bit integers? Any reason for not saving the props using always the widest possible type?

BTW, the docstring of Mol GetBoolProp wrapper seems to be wrong.

**Comment by bp-kelley** [comment]
@JLVarjo thanks for the GetBoolProp docstring report.  I also noticed a bug in the GetPropsAsDict as well that should be fixed.

The reason for using Int and Unsigned in 32 bits is to make it compatible with the C++ internals which do the same thing.  There is no reason not add Long versions, however in Python every type needs to be declared (in C++ you can actually add any type) and Int and UnsignedInt have special meaning in C land.

One nifty thing is that you can add/adjust properties that you can now use as queries in various ways based on a previous semi-non-obvious commit (i.e. as queries in substructure searches for example)

see HasPropWithValueQuery in https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/QueryOps.h

or as a python example in (HasDouble/Int...PropWithValueQueryAtom) what a mouth full that is:

```
[x.GetIdx() for x in m.GetAtomsMatchingQuery(
      rdqueries.HasDoublePropWithValueQueryAtom("boot", 1.0, tolerance=3.))]
```

Also, note that data stored as SDData can be retrieved numerically.

```
for m in Chem.SDMolSupplier("rdkit//Projects/DbCLI/testData/bzr.sdf"):
    print list(m.GetPropNames())
    print repr(m.GetProp("ACTIVITY"))
    print repr(m.GetDoubleProp("ACTIVITY"))
```

```
['ACTIVITY']
8.38
'8.38'
```

When in doubt, just retrieve the data as a double.  If is isn't a double, it will throw a RuntimeError (which as I note now should probably be converted into a python ValueError)  I'll make an issue so I don't forget.

```
['ACTIVITY']
'>6.87'
  File "test.py", line 18, in <module>
    print repr(m.GetDoubleProp("ACTIVITY"))
RuntimeError: boost::bad_any_cast: failed conversion using boost::any_cast
```

**Comment by bp-kelley** [comment]
@JLVarjo Thanks for making me look at this more in depth, I added the following issue:

https://github.com/rdkit/rdkit/issues/731

**Comment by JLVarjo** [comment]
Sorry for being unclear in my previous comment. What I actually suggested was that props set with python int wrappers could always end up to C++ side as 64-bit integers, to be safe. Despite not facing such a situation atm, I could imagine a case where someone wants to save e.g. database indices or file offsets as props, where 32-bit ints might not be sufficient. And as the future will probably be Python 3 run (mainly) in 64-bit systems, the integers will already be 64-bit in python side too, right? But feel free to object again :)

**Comment by bp-kelley** [comment]
Because a user might want to modify existing C++ int props, we will need to make a second function (SetLongInt).  I agree that this isn't very pythonic, but we are somewhat hampered by interaction with the C++ core.

Just so you know, the python wrappers have overflow protection:

```
>>> m = Chem.Mol()
>>> m.SetIntProp("foo", 2147483648)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: bad numeric conversion: positive overflow
```

Currently (as opposed to a LongInt) you could always store the values in a double
```
>>> m.SetDoubleProp("foo", 2147483648)
>>> m.GetProp("foo")
'2147483648'
```

**Comment by JLVarjo** [comment]
Thanks for the answer! Now being convinced that default 64-bit int is not feasible, I agree that SetLongInt is the only option. Which I can implement myself if I happen to need it some day. Anyway, thanks again for this enchancement, my stuff involves lots of prop transfer between python & C++, and now the expensive string conversions can be avoided.
