### ISSUE TITLE
Cannot import Draw

### ISSUE THREAD

**Issue by davidkuter** [rdkit/rdkit#4904]
**Describe the bug**
I cannot import Draw module in the latest rdkit release (2021-09-4). When attempting to import, I get the following circular import error:

```
ImportError: cannot import name 'rdMolDraw2D' from partially initialized module 'rdkit.Chem.Draw' (most likely due to a circular import) (/home/dkuter/scratch/rdkit_versions/rdkit_2021-09-4/lib/rdkit/rdkit/Chem/Draw/__init__.py)
```

**To Reproduce**
In a python terminal (3.8):

```
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit.Chem import Draw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dkuter/scratch/rdkit_versions/rdkit_2021-09-4/lib/rdkit/rdkit/Chem/Draw/__init__.py", line 14, in <module>
    from rdkit.Chem.Draw import rdMolDraw2D
ImportError: cannot import name 'rdMolDraw2D' from partially initialized module 'rdkit.Chem.Draw' (most likely due to a circular import) (/home/dkuter/scratch/rdkit_versions/rdkit_2021-09-4/lib/rdkit/rdkit/Chem/Draw/__init__.py)
```

**Expected behavior**
The Draw module should successfully import

**Screenshots**
N/A

**Configuration (please complete the following information):**
 - RDKit version: 2021-09-4
 - OS: Ubuntu 20.04
 - Python version (if relevant): 3.8
 - Are you using conda? No
 - If you are using conda, which channel did you install the rdkit from? N/A
 - If you are not using conda: how did you install the RDKit? Source

**Additional context**
N/A

**Comment by greglandrum** [comment]
I believe this is a problem with your local build. It's not something that happens with the conda-forge builds:
```
In [1]: import rdkit

In [2]: print(rdkit.__version__)
2021.09.4

In [3]: from rdkit.Chem import Draw
```

Did the _exact_ build environment+build commands you are using for 2021.09.4 work with 2021.09.3?

**Comment by davidkuter** [comment]
Hi Greg,

Thanks for the reply. It's definitely something I am doing in the install - I use a custom installer script ([here](https://github.com/cyclica/rdkit-installer/blob/master/install-rdkit)) to set up rdkit but something must have changed recently which is leading to these errors. Even when reinstalling older releases which previously worked, I am getting the circular import error. I'll see if I can pinpoint what change caused this!

**Comment by greglandrum** [comment]
I'm going to mark this as "not a bug" for the moment. We can switch it back if it turns out that this actually is an RDKit issue.

**Comment by greglandrum** [comment]
Glad you found it!

And thanks for the thanks. :-)
