### PR TITLE
Revert "ChemDraw Document and read/write support for the RDKit"

### PR DESCRIPTION
**Pull request by greglandrum**
Reverts rdkit/rdkit#8539

### CODE REVIEW

**Comment by greglandrum** [comment]
@bp-kelley I had assumed that everything was ok here because the CI builds went through, but the moment I updated my local copy of the RDKit and tried to do a clean build on linux with g++ 11.4, I got this:
```
In file included from /scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/CDXUnicode.cpp:39:
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h:6:8: error: ‘vector’ in namespace ‘std’ does not name a template type
    6 |   std::vector<T> buffer;
      |        ^~~~~~
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h:3:1: note: ‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?
    2 | #include "cs_assert.h"
  +++ |+#include <vector>
    3 | // stupid implementation
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h: In constructor ‘auto_buffer<T>::auto_buffer(unsigned int)’:
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h:8:40: error: class ‘auto_buffer<T>’ does not have any field named ‘buffer’
    8 |   auto_buffer(unsigned num_elements) : buffer(num_elements) {
      |                                        ^~~~~~
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h: In member function ‘size_t auto_buffer<T>::length() const’:
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h:13:34: error: ‘buffer’ was not declared in this scope; did you mean ‘setbuffer’?
   13 |   size_t length() const { return buffer.size(); }
      |                                  ^~~~~~
      |                                  setbuffer
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h: In member function ‘T* auto_buffer<T>::ptr()’:
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h:14:28: error: ‘buffer’ was not declared in this scope; did you mean ‘setbuffer’?
   14 |         T* ptr() { return &buffer[0]; }
      |                            ^~~~~~
      |                            setbuffer
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h: In member function ‘const T* auto_buffer<T>::ptr() const’:
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h:15:34: error: ‘buffer’ was not declared in this scope; did you mean ‘setbuffer’?
   15 |   const T* ptr() const { return &buffer[0]; }
      |                                  ^~~~~~
      |                                  setbuffer
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h: In member function ‘T auto_buffer<T>::operator[](unsigned int)’:
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h:17:44: error: ‘buffer’ was not declared in this scope; did you mean ‘setbuffer’?
   17 |         T  operator[](unsigned i) { return buffer[i]; }
      |                                            ^~~~~~
      |                                            setbuffer
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h: In member function ‘const T auto_buffer<T>::operator[](unsigned int) const’:
/scratch/RDKit_git/External/ChemDraw/chemdraw/chemdraw/cs_auto_buffer.h:18:49: error: ‘buffer’ was not declared in this scope; did you mean ‘setbuffer’?
   18 |   const T operator[](unsigned i) const { return buffer[i]; }
      |                                                 ^~~~~~
      |                                                 setbuffer

```

Looking at the code, that file (https://github.com/Glysade/chemdraw/blob/main/chemdraw/cs_auto_buffer.h) does not include vector.

**Comment by greglandrum** [comment]
I've reverted the merge of the chemdraw code because I'm sure I'm not the only one who will encounter this problem.
Please make sure the headers for the Glysade chemdraw library actually import everything that's required and then re-open the PR.

**Comment by greglandrum** [comment]
To everyone else: sorry for the noise caused by me merging this without having tested it thoroughly myself. There is a danger in over-reliance on the CI builds.
