### PR TITLE
Do a windows DLL build as part of the Azure DevOps setup

### PR DESCRIPTION
**Pull request by greglandrum**
Windows DLL build problems never get detected until @ptosco does a build manually and has to file an issue and submit a patch.

Seems like we can automate that. :-)

### CODE REVIEW

**Comment by bp-kelley** [comment]
Ironically the failing build actually proves the point!  This is being resolved in #2740 

```
     Creating library D:/a/1/s/build/Code/SimDivPickers/Wrap/Release/rdSimDivPickers.lib and object D:/a/1/s/build/Code/SimDivPickers/Wrap/Release/rdSimDivPickers.exp
LeaderPicker.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl RDPickers::LeaderPicker::LeaderPicker(void)" (__imp_??0LeaderPicker@RDPickers@@QEAA@XZ) referenced in function "public: static void __cdecl boost::python::objects::make_holder<0>::apply<struct boost::python::objects::value_holder<class RDPickers::LeaderPicker>,struct boost::mpl::vector0<struct boost::mpl::na> >::execute(struct _object *)" (?execute@?$apply@U?$value_holder@VLeaderPicker@RDPickers@@@objects@python@boost@@U?$vector0@Una@mpl@boost@@@mpl@4@@?$make_holder@$0A@@objects@python@boost@@SAXPEAU_object@@@Z) [D:\a\1\s\build\Code\SimDivPickers\Wrap\rdSimDivPickers.vcxproj]
LeaderPicker.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl RDPickers::LeaderPicker::~LeaderPicker(void)" (__imp_??1LeaderPicker@RDPickers@@UEAA@XZ) referenced in function "public: virtual void * __cdecl boost::python::objects::value_holder<class RDPickers::LeaderPicker>::`scalar deleting destructor'(unsigned int)" (??_G?$value_holder@VLeaderPicker@RDPickers@@@objects@python@boost@@UEAAPEAXI@Z) [D:\a\1\s\build\Code\SimDivPickers\Wrap\rdSimDivPickers.vcxproj]
LeaderPicker.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl RDPickers::LeaderPicker::LeaderPicker(class RDPickers::LeaderPicker const &)" (__imp_??0LeaderPicker@RDPickers@@QEAA@AEBV01@@Z) referenced in function "public: static struct _object * __cdecl boost::python::objects::class_cref_wrapper<class RDPickers::LeaderPicker,struct boost::python::objects::make_instance<class RDPickers::LeaderPicker,struct boost::python::objects::value_holder<class RDPickers::LeaderPicker> > >::convert(class RDPickers::LeaderPicker const &)" (?convert@?$class_cref_wrapper@VLeaderPicker@RDPickers@@U?$make_instance@VLeaderPicker@RDPickers@@U?$value_holder@VLeaderPicker@RDPickers@@@objects@python@boost@@@objects@python@boost@@@objects@python@boost@@SAPEAU_object@@AEBVLeaderPicker@RDPickers@@@Z) [D:\a\1\s\build\Code\SimDivPickers\Wrap\rdSimDivPickers.vcxproj]
  Building Custom Rule D:/a/1/s/Code/Numerics/CMakeLists.txt
  CMake does not need to re-run because D:/a/1/s/build/Code/Numerics/CMakeFiles/generate.stamp is up-to-date.
```

**Comment by bp-kelley** [comment]
@greglandrum I can't restart a new windows build, but the build should succeed now, want to try and restart?   I've approved the PR so feel free to merge.

**Comment by ptosco** [comment]
@greglandrum OK, that worked. I'll update #2742 with this additional fix.

File: External/RingFamilies/CMakeLists.txt [hunk 1]
```diff
@@ -23,6 +23,15 @@ set(urflib_INCLUDE_DIRS ${URFLIB_DIR}
     CACHE STRING "RingDecomposerLib Include Dir" FORCE)
 file(GLOB URFSOURCES "${URFLIB_DIR}/*.c")
 
+if((MSVC AND RDK_INSTALL_DLLS_MSVC) OR ((NOT MSVC) AND WIN32))
+    add_definitions("-DRDKIT_URFLIB_BUILD")
+    set (ringdecomposerlib_h ${URFLIB_DIR}/RingDecomposerLib.h)
+    file(READ ${ringdecomposerlib_h} ringdecomposerlib_h_data)
+    if (NOT "${ringdecomposerlib_h_data}" MATCHES "RDKIT_URFLIB_BUILD")
```
Comment (greglandrum) [inline External/RingFamilies/CMakeLists.txt]: Is it worth thinking about doing a PR against the ringdecomposerlib upstream repo so that this isn't necessary?
