### ISSUE TITLE
Apple Clang rejects emplace_back on aggregate Bounds struct in BoundsMatrixBuilderDetails.h (parenthesized aggregate init)

### ISSUE THREAD

**Issue by pechersky** [rdkit/rdkit#9579]
**Describe the bug**
On `Release_2026_03_5` (introduced by #9405), building `Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp` on macOS arm64 with Apple Clang (Xcode 15.4) fails with a "no matching constructor" error for `collected14Bounds[pid].emplace_back(dl, du, aid1, aid4)`, because Bounds (in BoundsMatrixBuilderDetails.h) is a plain aggregate with no user-declared constructors, yet is also constructed via designated-initializer brace-init elsewhere (merge()). Apple Clang enforces C++20 aggregate/parenthesized-init rules more strictly than GCC/MSVC/Linux Clang for this mixed pattern.

**To Reproduce**
Compile this with Clang 15 and libc++ using  `-std=c++20 -stdlib=libc++` like here https://www.godbolt.org/z/vY65vfW4d:

```
#include <vector>

struct Bounds {
  double lower{1.0};
  double upper{-1.0};
  unsigned int aid1{0};
  unsigned int aid4{0};
};

int main() {
  std::vector<Bounds> bounds;
  bounds.emplace_back(1.0, 2.0, 3u, 4u);
}
```

Compilation fails with:

```
error: no matching function for call to 'construct_at'
note: no matching constructor for initialization of 'Bounds'
```

**Expected behavior**
The file should compile cleanly on Apple Clang/Xcode, matching behavior on GCC/MSVC/Linux Clang.

**Configuration (please complete the following information):**
 - RDKit version: Releast_2026_03_5 and later
 - OS: macOS arm64
 - Python version (if relevant): all
 - Are you using conda? no
 - If you are using conda, which channel did you install the rdkit from? n/a
 - If you are not using conda: how did you install the RDKit? manual build,  Apple Clang, Xcode 15.4

**Additional context**
Suggested fix: Add an explicit constructor to Bounds matching the 4-argument emplace_back call site, or switch the emplace_back call to brace-init, consistent with the precedent fix in #9042 for the analogous BestAlignmentParams aggregate.

**Comment by greglandrum** [comment]
I believe that this is a bug in clang-15.
It is legal in C++20 to do aggregate initialization like this in an emplace_back.
If you switch the compler in godbolt to clang-16 everything is fine.

I think that this means that everything should work in versions of XCode>16. Given that XCode 16 was released 2 years ago, I don't see a strong argument for adding additional code to the RDKit to work around this particular compiler bug.

@pechersky is there a reason that you can't switch to a more up-to-date (and standard-compliant) version of the compiler?

**Comment by pechersky** [comment]
We were using `macos-14` github runners for MacOS builds, which have Sonoma. Those will be EOL in November, so we'll just switch to `macos-15` (xcode 16) now.
