### ISSUE TITLE
RDKit fail to compile on Windows 10 with mingw64 (gcc 7.2.0)

### ISSUE THREAD

**Issue by gmrandazzo** [rdkit/rdkit#1589]
**Description:**
RDKit fail to compile in a linking phase. 
Cmake try to link libRDKitChemReactions.dll (and also the filterCatalogTest.exe) with "FilterCatalog" but someting went wrong.

Here my configuration:

- Boost version 1.64
- Python version 2.7.14
- MSYS2 mingw64 
- Windows 10 (64bit)  (C:/WINDOWS/SysWOW64/msvcr100.dll)

Best regards,
GMR

cmake -G "MinGW Makefiles" -DRDK_BUILD_CAIRO_SUPPORT=ON -DRDK_BUILD_AVALON_SUPPORT=ON -DRDK_BUILD_INCHI_SUPPORT=ON -DMSVC_RUNTIME_DLL=C:/WINDOWS/SysWOW64/msvcr100.dll -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DRDK_BUILD_SWIG_JAVA_WRAPPER="OFF" ..

[ 88%] Linking CXX executable filterCatalogTest.exe
[ 88%] Built target testFragCatalog
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.text+0x670): undefined reference to `RDKit::FilterCatalogEntry::setDescription(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.text+0x69e): undefined reference to `RDKit::FilterCatalogEntry::getDescription[abi:cxx11]() const'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.text+0x996): undefined reference to `RDKit::FilterCatalogEntry::setDescription(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.text+0x9bc): undefined reference to `RDKit::FilterCatalogEntry::getDescription[abi:cxx11]() const'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.text+0x131d): undefined reference to `RDKit::FilterCatalogParams::addCatalog(RDKit::FilterCatalogParams::FilterCatalogs)'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.text+0x132f): undefined reference to `RDKit::FilterCatalogParams::addCatalog(RDKit::FilterCatalogParams::FilterCatalogs)'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.text+0x133c): undefined reference to `RDKit::FilterCatalogParams::addCatalog(RDKit::FilterCatalogParams::FilterCatalogs)'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.text+0x1496): undefined reference to `RDKit::FilterCatalog::setCatalogParams(RDKit::FilterCatalogParams*)'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.text+0x17c0): undefined reference to `RDKit::FilterCatalog::hasMatch(RDKit::ROMol const&) const'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.text+0x1833): undefined reference to `RDKit::FilterCatalog::getFirstMatch(RDKit::ROMol const&) const'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.text+0x2766): undefined reference to `RDKit::FilterCatalog::~FilterCatalog()'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.text+0x28cd): undefined reference to `RDKit::FilterCatalog::~FilterCatalog()'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.rdata$.refptr._ZTVN5RDKit13FilterCatalogE[.refptr._ZTVN5RDKit13FilterCatalogE]+0x0): undefined reference to `vtable for RDKit::FilterCatalog'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.rdata$.refptr._ZTVN5RDKit13SmartsMatcherE[.refptr._ZTVN5RDKit13SmartsMatcherE]+0x0): undefined reference to `vtable for RDKit::SmartsMatcher'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.rdata$.refptr._ZTVN5RDKit18FilterCatalogEntryE[.refptr._ZTVN5RDKit18FilterCatalogEntryE]+0x0): undefined reference to `vtable for RDKit::FilterCatalogEntry'
CMakeFiles\filterCatalogTest.dir/objects.a(filtercatalogtest.cpp.obj):filtercatalogtest.cpp:(.rdata$.refptr._ZTVN5RDKit19FilterCatalogParamsE[.refptr._ZTVN5RDKit19FilterCatalogParamsE]+0x0): undefined reference to `vtable for RDKit::FilterCatalogParams'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [Code\GraphMol\FilterCatalog\CMakeFiles\filterCatalogTest.dir\build.make:111: Code/GraphMol/FilterCatalog/filterCatalogTest.exe] Error 1
[ 88%] Built target testRDF
mingw32-make[1]: *** [CMakeFiles\Makefile2:4651: Code/GraphMol/FilterCatalog/CMakeFiles/filterCatalogTest.dir/all] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....
[ 88%] Built target testMORSE
[ 88%] Built target testPBF
[ 88%] Linking CXX shared library ..\..\..\bin\libRDKitChemReactions.dll
CMakeFiles\ChemReactions.dir/objects.a(PreprocessRxn.cpp.obj):PreprocessRxn.cpp:(.text+0x2c): undefined reference to `RDKit::GetFlattenedFunctionalGroupHierarchy[abi:cxx11](bool)'
CMakeFiles\ChemReactions.dir/objects.a(PreprocessRxn.cpp.obj):PreprocessRxn.cpp:(.text+0x252): undefined reference to `RDKit::GetFlattenedFunctionalGroupHierarchy[abi:cxx11](bool)'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [Code\GraphMol\ChemReactions\CMakeFiles\ChemReactions.dir\build.make:496: bin/libRDKitChemReactions.dll] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:3953: Code/GraphMol/ChemReactions/CMakeFiles/ChemReactions.dir/all] Error 2
mingw32-make: *** [Makefile:162: all] Error 2

**Comment by thegodone** [comment]
Dear Marco,

Please take yesterday afternoon commit, there may an issue since yesterday evening.

BR,

Guillaume

Envoyé de mon iPhone

**Comment by gmrandazzo** [comment]
Dear Guillaume, 

Thanks for your fast reply.
The problem is also present in the latest git commit. 

The error seems to be in Code/GraphMol/FilterCatalog/" and something related to the compiler, C++-11 and the ABI. 

I will try to recompile with the option "-D_GLIBCXX_USE_CXX11_ABI=0"  since:

"If you get linker errors about undefined references to symbols that involve types in the std::__cxx11 namespace or the tag [abi:cxx11] then it probably indicates that you are trying to link together object files that were compiled with different values for the _GLIBCXX_USE_CXX11_ABI macro. This commonly happens when linking to a third-party library that was compiled with an older version of GCC. If the third-party library cannot be rebuilt with the new ABI then you will need to recompile your code with the old ABI. " (ref. https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html)

Maybe the binary boost version was compiled with an old gcc compiler.

Saluti,
Marco
