### ISSUE TITLE
problem with compilation of cartridge Release_2016.09.2  

### ISSUE THREAD

**Issue by mjamroz** [rdkit/rdkit#1193]
Hello, 
I've postgres 9.1, and gcc 4.7.2
I am trying to compile rdkit release **Release_2016.09.2**  with cartridge:
`cmake .. -DRDK_BUILD_PGSQL=ON  -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/9.1/server/ -DPostgreSQL_ROOT=/usr -DRDK_BUILD_INCHI_SUPPORT=ON .. && make`

to get: 

> In file included from /var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/adapter.cpp:74:0:
> /var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/rdkit.h:56:12: error: /FLEXIBLE_ARRAY_MEMBER’ was not declared in this scope
> /var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/adapter.cpp:549:24: warning: unused parameter ‘i’ [-Wunused-parameter]
> /var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/adapter.cpp:549:24: warning: unused parameter ‘opts’ [-Wunused-parameter]
> /var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/adapter.cpp:570:24: warning: unused parameter ‘i’ [-Wunused-parameter]
> /var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/adapter.cpp:570:24: warning: unused parameter ‘opts’ [-Wunused-parameter]
> /var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/adapter.cpp: In function ‘BfpSignature* makeBfpSignature(CBfp)’:
> /var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/adapter.cpp:749:15: error: ‘struct BfpSignature’ has no member named ‘fp’

however on the same machine, release **Release_2016.03.5** compiled successfully.
Is postgresql>9.1 needed for newer releases?

Thanks for your great rdkit work!

PS I tried to disable most of things:
 RDK_BUILD_AVALON_SUPPORT OFF                                                                                                                                                         
 RDK_BUILD_CAIRO_SUPPORT          OFF                                                                                                                                                         
 RDK_BUILD_COMPRESSED_SUPPLIERS   OFF                                                                                                                                                         
 RDK_BUILD_CONTRIB                OFF                                                                                                                                                         
 RDK_BUILD_CPP_TESTS              OFF                                                                                                                                                         
 RDK_BUILD_DESCRIPTORS3D          OFF                                                                                                                                                         
 RDK_BUILD_INCHI_SUPPORT          OFF                                                                                                                                                         
 RDK_BUILD_PGSQL                  ON                                                                                                                                                          
 RDK_BUILD_PYTHON_WRAPPERS        OFF                                                                                                                                                         
 RDK_BUILD_QT_DEMO             OFF                                                                                                                                                         
 RDK_BUILD_QT_SUPPORT             OFF                                                                                                                                                         
 RDK_BUILD_SLN_SUPPORT            OFF                                                                                                                                                         
 RDK_BUILD_SWIG_CSHARP_WRAPPER    OFF                                                                                                                                                         
 RDK_BUILD_SWIG_JAVA_WRAPPER      OFF
 RDK_BUILD_SWIG_WRAPPERS          OFF                                                                                                                                                         
 RDK_BUILD_TEST_GZIP              OFF                                                                                                                                                         
 RDK_BUILD_THREADSAFE_SSS         OFF                                                                                                                                                         
 RDK_INSTALL_INTREE               ON                                                                                                                                                          
 RDK_INSTALL_STATIC_LIBS          ON                                                                                                                                                          
 RDK_OPTIMIZE_NATIVE              ON                                                                                                                                                          
 RDK_PGSQL_STATIC                 ON                                                                                                                                                          
 RDK_TEST_COVERAGE                OFF                                                                                                                                                         
 RDK_TEST_MMFF_COMPLIANCE         OFF                                                                                                                                                         
 RDK_TEST_MULTITHREADED           OFF                                                                                                                                                         
 RDK_USE_BOOST_SERIALIZATION      OFF                                                                                                                                                         
 RDK_USE_FLEXBISON                OFF                                                                                                                                                         
 RDK_USE_STRICT_ROTOR_DEFINITIO   OFF    
and still the same errors

**Comment by greglandrum** [comment]
We are working on a patch to get things working with v9.2.
I wasn't planning on testing against 9.1 given that it is no longer supported by the PostgreSQL developers, but it may be that the new patch, once applied, helps you too.

**Comment by rvianello** [comment]
I'm afraid this is a different problem, but it might be easy to work around. I think replacing line 

https://github.com/rdkit/rdkit/blob/Release_2016_09_2/Code/PgSQL/rdkit/rdkit.h#L56
`  uint8 fp[FLEXIBLE_ARRAY_MEMBER];`

with:

`  uint8 fp[];`

is likely to work with most compilers. Alternatively

`  uint8 fp[1];`

should work also when empty array definitions at the end of a struct are not yet supported.

Sorry for the issue,

**Comment by rvianello** [comment]
a proper backward-compatibility fix would of course use some preprocessor conditionals based on the postgres version, but I hope the above may help fix this build.

**Comment by mjamroz** [comment]
How fast, thanks!
I changed source, as @rvianello suggested. Got the sam error with rest of `FLEXIBLE_ARRAY_MEMBER` (first - changed to `[]`, later - to `[1]`), and now I got this:
>[ 98%] Building C object Code/PgSQL/rdkit/CMakeFiles/rdkit.dir/bfp_gist.c.o
>[ 98%] Building C object Code/PgSQL/rdkit/CMakeFiles/rdkit.dir/bfp_gin.c.o
>/var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/bfp_gin.c: In function ‘gin_bfp_triconsistent’:
>/var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/bfp_gin.c:168:3: error: unknown type name ‘GinTernaryValue’
>/var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/bfp_gin.c:168:29: error: ‘GinTernaryValue’ undeclared (first use in this function)
>/var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/bfp_gin.c:168:29: note: each undeclared identifier is reported only once for each function it appears in
>/var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/bfp_gin.c:168:46: error: expected expression before ‘)’ token
>/var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/bfp_gin.c:177:19: error: expected ‘;’ before ‘result’
>/var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/bfp_gin.c:181:21: error: ‘GIN_TRUE’ undeclared (first use in this function)
>/var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/bfp_gin.c:185:26: error: ‘GIN_MAYBE’ undeclared (first use in this function)
>/var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/bfp_gin.c:197:8: error: ‘result’ undeclared (first use in this function)
/>var/opt/rdkit/rdkit-Release_2016_09_2/Code/PgSQL/rdkit/bfp_gin.c:197:17: error: ‘GIN_FALSE’ undeclared (first use in this function)
>make[2]: *** [Code/PgSQL/rdkit/CMakeFiles/rdkit.dir/bfp_gin.c.o] Error 1
>make[1]: *** [Code/PgSQL/rdkit/CMakeFiles/rdkit.dir/all] Error 2
>make: *** [all] Error 2

It probably looks that I need postgres >9.1. Thanks for your help, tomorrow, i would try to update to 9.2.

**Comment by greglandrum** [comment]
@mjamroz: if it's possible on your system, I would recommend updating to as modern a version of PostgreSQL as you can (9.5 or 9.6). This isn't always possible, particularly if you are constrained by what is offered by your operating system packager, but the newer versions add nice functionality.
As an FYI: v9.2 will be going out of support in Sept 2017: https://www.postgresql.org/support/versioning/

**Comment by mjamroz** [comment]
i had installed postgreSQL 9.5 and of course rdkit cartridge works like a charm. Thanks for your great work, guys!

**Comment by JimSEOW** [comment]
Has anyone has success with using the latest rdkit cartridge to work with PostgreSQL (9.5 or 9.6) for Win64 Windows 10?  The last time I tried (~3-4 weeks ago) the rdkit cartridge  does not work with PostgreSQL 9.6 in the above settings
